### ISSUE TITLE
plugin has a package.json but not published on npm

### ISSUE THREAD

**Issue by fephil** [javve/list.fuzzysearch.js#10]
Hi,

Could this plugin be published onto npm? I noticed the package.json file has been made but the plugin hasn't been published.

Thanks!

**Comment by fephil** [comment]
For info, this works in npm as expected until the plugin is published:

`npm i javve/list.fuzzysearch.js#v0.1.0 --save`

**Comment by javve** [comment]
I'll make sure it's published for the next release! :+1:

**Comment by Spone** [comment]
Hello, still not published on npm?

**Comment by mrcsmcln** [comment]
+1
