### ISSUE TITLE
How do you pass fuzzyOptions to the plugin?

### ISSUE THREAD

**Issue by ryanmortier** [javve/list.fuzzysearch.js#9]
This documentation is a bit vague on how to use fuzzyOptions.

``` javascript
<div id="list-id">
  <input class="fuzzy-search" />
  <ul class="list">
    / A bunch of items /
  </ul>
</div>

<script>

var fuzzyOptions = {
  searchClass: "fuzzy-search",
  location: 0,
  distance: 100,
  threshold: 0.4,
    multiSearch: true
};
var options = {
  valueNames: [ 'name', 'category' ],
  plugins: [
    ListFuzzySearch()
  ]
};

var listObj = new List('list-id', options);

// Search manually 
listObj.fuzzySearch.search('my search');

// Search manually on specific columns
listObj.fuzzySearch.search('my search', { name: true });

</script>
```

If I just follow that exactly, I can't actually get any of the threshold, location, distance options to work. I took a chance and did this:

```
plugins: [ ListFuzzySearch(fuzzyOptions) ]
```

and magically it started working. Is this the correct syntax?

I have an older application using an older version of fuzzy search and the syntax is like so:

```
plugins: [  [ 'fuzzySearch', fuzzyOptions ]  ]
```

The current documentation doesn't really explain how to utilize fuzzyOptions.

**Comment by hyteckit** [comment]
The correct way is:

`plugins: [ ListFuzzySearch(fuzzyOptions) ]`

Problem is that there is an error in the source code.  

You can fix the code by

Changing:

`    extend({
        location: 0,
        distance: 100,
        threshold: 0.4,
        multiSearch: true,
        searchClass: 'fuzzy-search'
    }, options);`

To:

`    options = extend({
        location: 0,
        distance: 100,
        threshold: 0.4,
        multiSearch: true,
        searchClass: 'fuzzy-search'
    }, options);`

**Comment by michaelsalmons** [comment]
I would be interested in a complete source for this, if possible. I've tried making these changes to my local install and it's broken. I'd attach a file but I probably just don't know how to do it properly.
